FROM almalinux:9

RUN dnf install nginx -y
RUN rm -f /usr/share/nginx/html/index.html

ADD https://raw.githubusercontent.com/pothuguntarakesh3388/dockerfiles/refs/heads/main/ADD/Dockerfile /usr/share/nginx/html/index.html
RUN chmod +x /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]
